#index:
#    path: /
#    controller: App\Controller\DefaultController::index
profile:
    path: '/profile'
    controller: 'App\Controller\ProfileController::show'
app_user_edit:
    path: '/user/edit/{id}'
    controller: 'App\Controller\UserController::edit'
pdf:
    path: '/pdf'
    controller: 'App\Controller\UserController::generatePdfAction'